version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cl_shop
      MYSQL_USER: cl_user
      MYSQL_PASSWORD: cluserpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password  # Set Neo4j username/password
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol for queries
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  neo4j_data:
  neo4j_logs:
  mongo_data:

